#pragma once

// Generated by tools/generate_tiago_dynamics.py from the native Tiago URDF.
// These limits are the raw URDF limits for the right arm. Safety margins belong
// in solver policy/tuning code, not in this source-of-truth robot data.

namespace gato {
namespace plant {

        constexpr int TIAGO_LIMIT_JOINTS = 7;

        template<class T>
        __device__ constexpr T JOINT_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-4.7123889438808), static_cast<T>(0.52359877154231105)},  // arm_right_1_joint
            {static_cast<T>(-2.4434609338641202), static_cast<T>(1.1344640050083401)},  // arm_right_2_joint
            {static_cast<T>(-2.61799385771155), static_cast<T>(2.61799385771155)},  // arm_right_3_joint
            {static_cast<T>(-2.4434609338641202), static_cast<T>(1.1344640050083401)},  // arm_right_4_joint
            {static_cast<T>(-1.5707963146269299), static_cast<T>(3.6651914007961799)},  // arm_right_5_joint
            {static_cast<T>(-1.8849555775523199), static_cast<T>(3.0019662901759099)},  // arm_right_6_joint
            {static_cast<T>(-2.61799385771155), static_cast<T>(2.61799385771155)},  // arm_right_7_joint
        };

        template<class T>
        __device__ constexpr T VEL_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_1_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_2_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_3_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_4_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_5_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_6_joint
            {static_cast<T>(-2.5), static_cast<T>(2.5)},  // arm_right_7_joint
        };

        template<class T>
        __device__ constexpr T CTRL_LIMITS_DATA[TIAGO_LIMIT_JOINTS][2] = {
            {static_cast<T>(-43), static_cast<T>(43)},  // arm_right_1_joint
            {static_cast<T>(-43), static_cast<T>(43)},  // arm_right_2_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_3_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_4_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_5_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_6_joint
            {static_cast<T>(-26), static_cast<T>(26)},  // arm_right_7_joint
        };

        template<class T>
        __host__ __device__ constexpr const T (&JOINT_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return JOINT_LIMITS_DATA<T>;
        }

        template<class T>
        __host__ __device__ constexpr const T (&VEL_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return VEL_LIMITS_DATA<T>;
        }

        template<class T>
        __host__ __device__ constexpr const T (&CTRL_LIMITS())[TIAGO_LIMIT_JOINTS][2]
        {
                return CTRL_LIMITS_DATA<T>;
        }

}  // namespace plant
}  // namespace gato
